# Generated by Django 3.2 on 2022-10-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_balance',
            field=models.BigIntegerField(default=2000),
        ),
    ]
