# Generated by Django 3.2 on 2022-10-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('Bronze', 'Globalnet Bronze - 500 BDT // month, 12 months'), ('Silver', 'Globalnet Silver - 750 BDT / month, 12 months'), ('Gold', 'Globalnet Gold - 1500 BDT / month, no contract - You can cancel at any time')], max_length=200, null=True),
        ),
    ]
